#!/usr/bin/env python3
"""
Build the reading library's index page at {reading_dir}/index.html.

GENERATED by course-engine/reading/apply.py. The logic lives in
course-engine/reading/engine/index.py.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "reading_engine"))

import site_chrome
from reading_engine.engine import chrome as chrome_mod
from reading_engine.engine import common
from reading_engine.engine.index import IndexBuilder


def main():
    site = common.Site()
    p = IndexBuilder(site, chrome_mod.Chrome(site_chrome)).build()
    if not p:
        print("no readings yet; nothing to index")
        return 0
    print(f"  built {p.relative_to(site.root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
