#!/usr/bin/env python3
"""
Build {reading_dir}/{level}/{slug}.html from content/readings/{level}/{slug}.json.

GENERATED by course-engine/reading/apply.py. Do not edit: the logic lives in
course-engine/reading/engine/page.py, shared by every site in the family.
Edit it there and re-apply.

Usage:
    python3 scripts/build_reading_page.py                 # build all
    python3 scripts/build_reading_page.py a1/ma-journee   # build one
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))                    # the site's own scripts/
sys.path.insert(0, str(HERE / "reading_engine"))

import site_chrome
from reading_engine.engine import chrome as chrome_mod
from reading_engine.engine import common
from reading_engine.engine.page import Builder


def main():
    targets = sys.argv[1:]
    site = common.Site()
    builder = Builder(site, chrome_mod.Chrome(site_chrome))
    built = 0
    for level, slug, d in site.all_sources():
        if targets and f"{level}/{slug}" not in targets:
            continue
        p = builder.build(level, slug, d)
        print(f"  built {p.relative_to(site.root)}")
        built += 1
    if not built:
        print("nothing to build (no matching content/readings/*.json)")
        return 0
    print(f"{built} reading page(s) built")
    return 0


if __name__ == "__main__":
    sys.exit(main())
