#!/usr/bin/env python3
"""
Check the reading sources against the schema.

GENERATED by course-engine/reading/apply.py. The checks live in
course-engine/reading/engine/checks.py.

Usage:
    python3 scripts/check_reading.py              # errors only
    python3 scripts/check_reading.py --warnings   # errors and warnings
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "reading_engine"))

from reading_engine.engine import common
from reading_engine.engine.checks import check_one


def main():
    warnings = "--warnings" in sys.argv
    site = common.Site()
    n = errs = warns = 0
    for lv, sl, d in site.all_sources():
        n += 1
        e, w = check_one(site, lv, sl, d, warnings=warnings)
        if e or w:
            print(f"{lv}/{sl}")
            for x in e:
                print(f"  ERROR   {x}")
            for x in w:
                print(f"  warning {x}")
        errs += len(e)
        warns += len(w)
    print(f"\n{n} reading(s): {errs} error(s), {warns} warning(s)")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
