#!/usr/bin/env python3
"""
Narrate content/readings/*.json to assets/audio/reading/ with edge-tts.

GENERATED by course-engine/reading/apply.py. The logic lives in
course-engine/reading/engine/audio.py.

edge-tts is not a dependency of this repo, so point at one you have:

    python3 -m venv /tmp/rl-venv && /tmp/rl-venv/bin/pip install edge-tts
    python3 scripts/generate_reading_audio.py --tts /tmp/rl-venv/bin/edge-tts

Usage:
    python3 scripts/generate_reading_audio.py --check          # report only
    python3 scripts/generate_reading_audio.py a1/ma-journee [--force]
    python3 scripts/generate_reading_audio.py                  # all stale/missing
"""
import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "reading_engine"))

from reading_engine.engine import common
from reading_engine.engine.audio import Narrator


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("targets", nargs="*", help="level/slug, e.g. a1/ma-journee")
    ap.add_argument("--check", action="store_true",
                    help="report missing/stale audio, generate nothing")
    ap.add_argument("--force", action="store_true", help="regenerate even if up to date")
    ap.add_argument("--tts", help="path to the edge-tts executable")
    ap.add_argument("--stamp-durations", action="store_true",
                    help="write each narration's measured length back into its "
                         "source JSON as audio.duration_label (needs ffprobe)")
    args = ap.parse_args()

    site = common.Site()
    n = Narrator(site)
    items = [(lv, sl, d) for lv, sl, d in site.all_sources()
             if not args.targets or f"{lv}/{sl}" in args.targets]
    if not items:
        print("no matching content/readings/*.json")
        return 0

    if args.check:
        man = n.load_manifest()
        bad = [(lv, sl, why) for lv, sl, d in items if (why := n.is_stale(lv, sl, d, man))]
        for lv, sl, why in bad:
            print(f"  {why.upper():8} {lv}/{sl}")
        print(f"{len(items)} reading(s); {len(bad)} need audio")
        return 1 if bad else 0

    tts = n.find_tts(args.tts)
    if not tts:
        print("error: edge-tts not found. Create a venv as shown in this file's\n"
              "       docstring, then pass --tts /path/to/edge-tts", file=sys.stderr)
        return 2

    man = n.load_manifest()
    done = 0
    for lv, sl, d in items:
        if not args.force and not n.is_stale(lv, sl, d, man):
            print(f"  up to date {lv}/{sl}")
            continue
        out, voice, rate = n.generate(lv, sl, d, tts)
        man[f"{lv}/{sl}"] = {"fingerprint": n.fingerprint(d, voice, rate),
                             "voice": voice, "rate": rate, "bytes": out.stat().st_size}
        n.save_manifest(man)
        print(f"  narrated {out.relative_to(site.root)}  "
              f"({voice}, rate {rate}, {out.stat().st_size // 1024} KB)")
        done += 1
    print(f"{done} audio file(s) written")

    if args.stamp_durations:
        stamped = 0
        for lv, sl, _d in items:
            if n.stamp_duration(lv, sl):
                stamped += 1
        if stamped:
            print(f"{stamped} duration label(s) stamped into content/readings/")
        else:
            print("no durations stamped (is ffprobe installed?)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
